compile1:
# 	Compile your code for first part here
  gcc Q1_part1.c -o tst1
run1: compile1
# 	 Execute part 1 here
  ./tst1
compile2:
# 	Compile your code for second part here
  gcc Q1_part2.c -o tst2 -pthread
run2: compile2
#	Execute part 2 here
  ./tst2
